### ISSUE TITLE
How to capture complete data

### ISSUE THREAD

**Issue by liunx7594** [abhinavsingh/proxy.py#1145]
I spent three hours studying this project, but I still don't quite understand it. It seems that all the data captured are chunks. If I want to capture complete data, what should I do? For example, I can capture response Body? A complete HTML?

**Comment by abhinavsingh** [comment]
Try using the following command for starters:

`python -m proxy --plugins proxy.plugin.CacheResponsesPlugin --cache-by-content-type --ca-key-file ca-key.pem --ca-cert-file ca-cert.pem --ca-signing-key ca-signing-key.pem --num-acceptors 1`

Make a few requests and you shall see content under `~/.proxy/cache` directory.   You should see 2 folders:
1. `content` -- Contains parsed `jpg`, `css`, `js`, `html`, `pdf` etc by content type
2. `responses` -- Contains raw responses as received (of-course decrypted because of interception)

Once you have this running.  Study the related code and extend it as you wish.

Let me know how it goes. Best.

**Comment by liunx7594** [comment]
Thank you very much for your guidance. I have successfully captured some test website HTML. A great project.

**Comment by abhinavsingh** [comment]
You are welcome.  Glad it worked and helped you +1
