### ISSUE TITLE
How to configure reverse plugin correctly?

### ISSUE THREAD

**Issue by plotti** [abhinavsingh/proxy.py#1334]
Trying to point the reverse proxy plugin to anything else see screenshot:

<img width="696" alt="Bildschirmfoto 2023-05-22 um 17 36 22" src="https://github.com/abhinavsingh/proxy.py/assets/610885/14f2f791-1d5c-4388-9ab0-c3e7316d8e20">

When i go to the website i get:

<img width="1092" alt="Bildschirmfoto 2023-05-22 um 17 37 22" src="https://github.com/abhinavsingh/proxy.py/assets/610885/616120da-2a62-427f-bbd0-395d193258d1">

**Comment by plotti** [comment]
Why doesn't it stay on my local machine like i thought a reverse plugin does?

**Comment by plotti** [comment]
Also how can i change the website i receive on the fly? I want to use beautiul soup to exchange some site elements...

**Comment by abhinavsingh** [comment]
Hi @plotti , Currently reverse proxy eco-system don't support same plugin interface as our proxy server plugins.   This is because reverse proxy support was added mostly because it was technically possible, but I never found time to evolve/mature it.   Hence, it exists in more-or-less a prototype stage, where once can only choose between upstream URL choices.

This is something we are already planning for the next release, but that won't be out for at-least a month.

**Comment by abhinavsingh** [comment]
@plotti Looking back again at your original comment, shouldn't you visit the `<proxy-py-ip>:<port>` instead of the website directly?

**Comment by abhinavsingh** [comment]
> Why doesn't it stay on my local machine like i thought a reverse plugin does?

Try reaching your services behind reverse proxy on `http://<proxy-py-ip>:<port>`, instead of directly hitting the service endpoint in the browser.

**Comment by abhinavsingh** [comment]
> Also how can i change the website i receive on the fly? I want to use beautiul soup to exchange some site elements...

You can extend the example `ReverseProxyPlugin` to remove hardcoded upstream URLs and dynamically read them from a file/db/cache etc.   This will allow you to dynamically change the website being served to you

**Comment by abhinavsingh** [comment]
Please re-open if you have any further questions or something is not working as expected :D
