### ISSUE TITLE
Challenges subclassing, suggesting split

### ISSUE THREAD

**Issue by kidmose** [abhinavsingh/proxy.py#17]
Hi Abhinav and others, 

I'd like to build a customised proxy by subclassing your `proxy.py` but as it's a single file in `bin/`I believe I need to copy it out, complicating my workflow compared with simply `pip install proxy.py`.
Have you considered splitting it into a module (usefull in my case) and a runner with main method to be placed in bin?

Thanks for a nice piece of python :)

**Comment by abhinavsingh** [comment]
Hi @kidmose Its is a single file project due to its [past history and initial use case](https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/). Were you able to get around the limitation, example by, using proxy.py as a submodule within your project, which will allow proxy.py to live next to your project source code, allowing `from proxy.py import ...`

**Comment by kidmose** [comment]
Hi @abhinavsingh , 
I'm afraid can't recall the context where this issue appeared, nor can I find any code from back then. 
I have no concrete plans of doing this, but I'll keep it in mind as something that I could pick up on a rainy day :)
