### ISSUE TITLE
Feature idea: Add hooks for targeted redirects

### ISSUE THREAD

**Issue by sjlawsonAL** [abhinavsingh/proxy.py#30]
For a POC I've been working on, I added a couple lines to redirect certain requests to a mocked destination where the requests can be verified by an automated test suite. 
What do you think would be a good way to add this ability as a feature, like a hook function or a user-definable hash map?

For example- In my implementation, most requests simply pass through without being touched, however, when a request to api.segment.io enters the proxy, it gets redirected to a mocked api.

If you want, I could take a stab at it and submit a PR for you to review.

**Comment by abhinavsingh** [comment]
@sjlawsonAL Something on these lines is indeed desirable. I do envision an event-based API, so that `proxy.py` users can fully customize inner working and behavior. Previously, I described some of my thoughts here https://github.com/abhinavsingh/proxy.py/issues/28#issuecomment-430682501 too.

There can be multiple ways to provide such an API. To kickstart our discussion and just to throw out some rough ideas:

```
class MyProxyHandler(BaseProxyHandler):

    def handle_request(self):
        if self.host == 'api.segment.io':
            self.redirect(....)

    def handle_response(self):
        ...
```

and to make `proxy.py` aware of `MyProxyHandler`, we could do something on these lines:

```
./proxy.py --handler my.proxy.handler.module.MyProxyHandler .....
```

I am interested if better (alternate) ways exists or how can we further refine the above interface. Currently, I am targeting open bugs so that we can release `proxy.py v0.3` (which is currently under develop branch and not on pypi). But we can certainly work on this feature for `v0.4`.

Happy to see a PR and contributions towards this feature 👍

**Comment by abhinavsingh** [comment]
Several users have requested this feature via GitHub issues, e-mails and via [Stack](https://stackoverflow.com/questions/37451775/how-to-make-an-http-proxy-that-points-to-a-specific-server) [Overflow](https://stackoverflow.com/questions/53456993/filtering-on-top-of-already-developed-proxy).

**Comment by abhinavsingh** [comment]
@sjlawsonAL https://github.com/abhinavsingh/proxy.py/commit/77c7976fe2386d3b7f86fdd3398786e8832688ea introduces new plugins feature.  Feel free to take a look, feedback appreciated.  Thanks

**Comment by asieira** [comment]
I would like to suggest that the plugin mechanism also allow for request filtering. 

So in essence allow `handle_request` to cause the upstream connection to never be performed and a 403 response to be given to the client instead.

**Comment by abhinavsingh** [comment]
@sjlawsonAL @asieira unsure if you had a chance to look into recent API changes.  See https://github.com/abhinavsingh/proxy.py/blob/develop/plugin_examples.py for some examples and https://github.com/abhinavsingh/proxy.py/pull/64 description for details about the plugin system.

Marking this as closed since we now have a plugin system in place.  Happy to open up separate tracker for further iterations on plugin modules.  Thank you for putting up this request, we finally have something to kick start with.
