### ISSUE TITLE
[Plugins] Allow custom command line flags per plugin

### ISSUE THREAD

**Issue by trianta2** [abhinavsingh/proxy.py#301]
The cache directory seems to be hard-coded as a random temporary directory: https://github.com/abhinavsingh/proxy.py/blob/ae92adc432a143a9056eb2251f0cd8a40bcd8f64/proxy/plugin/cache/cache_responses.py#L28

Not sure why. Consider exposing this as a command line parameter, with default value of `None`, which results in a temporary directory.

**Comment by abhinavsingh** [comment]
Hi @trianta2 Thanks for reporting this.  Frankly, cache plugin (and other plugins) only exists for demonstration purposes, though with time they are maturing enough for production usage out of box.

Before command line flag for `cache_responses` plugin, `proxy.py` core will need to expose `Flags` class in a way that allows plugins to define custom command line parameters.

I have repurposed this issue to address core enhancement before adding a flag for `cache_responses` plugin.  Let me know if a cleaner or alternative & faster way exists for doing the same.

Cheers!!!

**Comment by trianta2** [comment]
Hi @abhinavsingh I forked your repo and implemented this quickly (i.e. added a `--cache-dir` argument to global flags, and accessed this CLI argument via the flags object passed to `CacheResponsesPlugin` as a positional argument). However I noticed that a new cached file was being made each request, instead of serving back cached responses as I had hoped. Indeed, the more general problem is exposing plugin parameters.

**Comment by abhinavsingh** [comment]
Nice!!!  Totally, cache responses plugin only caches.  It doesn't serves
out of cache.  As I mentioned, default plugins are mostly for demonstration
and showcases plugin capabilities.  These plugins will likely need more
work for production usage, but shouldn't be too much to add.

Global flag indeed works for one off usage, though I would love to expose
this functionality generically, so that each flag doesn't become global.  I
have a few thoughts about how we can do it.  If you would like to take a
stab at it, lemme know.  Happy to discuss further.

Thank you!!!
