### ISSUE TITLE
[Dashboard] Not found.  How to build it?

### ISSUE THREAD

**Issue by rolandelferink** [abhinavsingh/proxy.py#324]
I am trying to run your proxy.py and specifically, I want to see the dashboard but I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\roland\\PycharmProjects\\proxy.py\\proxy\\public\\dashboard\\proxy.html'
```

but if I try and find that file I see that the entire public directory within `proxy.py\proxy` is missing in the source code.

Where would I find this directory and it's contents?

**Comment by abhinavsingh** [comment]
Hi @rolandelferink 

Currently dashboard is a WIP and one needs to build it using `make dashboard`

You might also need to do `cd dashboard && npm install` (one time setup) before building the dashboard.

Lemme know how it goes. Thank you!!!

**Comment by abhinavsingh** [comment]
Got back to dashboard today.  Frankly it's a WIP and there ain't much to use currently on the dashboard.  But jFYI, one must also pass `--enable-dashboard` flag to view dashboard.   To recap all the steps:

1) Install node/npm
2) Install dashboard dependencies
     `pushd dashboard && npm install && popd`
3) Build dashboard
     `make dashboard`
4) Symlink built dashboard html/js/css files, so that it can be served via proxy.py static server
     `pushd proxy.py && ln -s ../dashboard/public public && popd`
5) Start proxy.py with dashboard enabled
     `python -m proxy --enable-dashboard`
6) Visit dashboard
     `open http://localhost:8899/dashboard/`

I'll close this issue as above steps list everything one needs to view the dashboard.  It's a WIP, if interested please reach out for development help.  Thank you.
