### ISSUE TITLE
[TLS Interception] WebSocket (wss) is not working

### ISSUE THREAD

**Issue by DEEP7696** [abhinavsingh/proxy.py#356]
Unable to connect to wss socket. Getting status 101.
Trying to access https://web.whatsapp.com/

 - OS: windows
 - Browser chrome, firefox

tls interception is enabled

![image](https://user-images.githubusercontent.com/26339251/83595375-6c9ed680-a57f-11ea-83ad-92d7e64cc948.png)

**Comment by abhinavsingh** [comment]
Hi @DEEP7696 , 101 is response code for switching protocols which is used by WebSocket.  I believe it is working as expected.  You can click on one of the request and inspect the messages tab.

**Comment by DEEP7696** [comment]
thanks abhinav now its working.

**Comment by DEEP7696** [comment]
when i monitored again:
now its dropping after 1 minute.
![image](https://user-images.githubusercontent.com/26339251/83860648-27c09e80-a73d-11ea-86ed-d0f9d2cbd358.png)

**Comment by abhinavsingh** [comment]
That's ok.  You can set timeout to 1 hour and it will still drop.  Note
that connection is only dropped if inactive.

Most importantly, this behavior will not impact the application or user
experience.  As you can see, WebSocket connections are
immediately re-created.

Are you experiencing any specific issue because of connection drop?

------------------------------------------------------
Abhinav Singh,
https://abhinavsingh.com
------------------------------------------------------

**Comment by DEEP7696** [comment]
yes,
you might have seen in the image i am unable to get QR code it just keeps loading.
even i tried with other websites which uses websocket are also just keeps loading. It is just happening when tls interception is on.

**Comment by abhinavsingh** [comment]
> yes,
> you might have seen in the image i am unable to get QR code it just keeps loading.
> even i tried with other websites which uses websocket are also just keeps loading. It is just happening when tls interception is on.

Thanks for reporting this.  Indeed looks like an issue with WebSocket when TLS Interception is on.  The problem persists even with new TLS interception certificate generation strategy (see https://github.com/abhinavsingh/proxy.py/pull/362).

Summary:
1. NOT a problem when TLS interception is OFF
2. This needs further investigation for TLS interception ON cases

**Comment by abhinavsingh** [comment]
Looks like `WebSocket` connections are being treated as `HTTP/1.1 Pipeline Requests`.  We do so because when TLS interception is enabled, we want to also intercept any pipelined requests. Offending section is over here https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/proxy/server.py#L206-L209

Proxy server should also not mark the `WebSocket` request as complete because technically it's a long lived connection.  By doing so, above block of code won't hit WebSockets workflow.

Will try to send out a patch this weekend. Cheers!!!

**Comment by abhinavsingh** [comment]
Please take a look, this should now be addressed.  Next week I'll make a new `pip`, `homebrew` and `docker` release.
