### ISSUE TITLE
[DoS] Vulnerability in proxy.py

### ISSUE THREAD

**Issue by NariyoshiChida** [abhinavsingh/proxy.py#567]
Hi @abhinavsingh!

I have found a DoS vulnerability in proxy.py and have sent an email to you on May 17th, but never gotten any response yet. The email contains the details of the vulnerability and how to reproduce/repair it. With regard to the Security Policy ( https://github.com/abhinavsingh/proxy.py/security/policy ), I create this issue.  I would like to directly show you the vulnerability in detail instead of disclosing it here in order to minimize the risk. Could you please check the email and consider fixing it?

Thank you.

**Comment by abhinavsingh** [comment]
Thank you @NariyoshiChida , looks like the email landed in my spam box because it was not encrypted :(. Apologies for the same.

One good thing is that, vulnerability is related to an example plugin, rather than the core library itself.  Example plugins are often community contributed and only serves as a demonstration of what can be achieved via plugins.  As advertised in the README.md, these plugins are not production ready.

Having said that, this is no reason to ship a vulnerability via example plugins.  I'll address this over the coming weekend.  Thank you for bringing this into my consideration.

Cheers!!!

**Comment by abhinavsingh** [comment]
@NariyoshiChida This was fixed and fix was sent out as part of v2.4.4 release.  Closing now.  Thanks again for reporting.
