### ISSUE TITLE
[PyInstaller] Workers don't shutdown when started from within a script

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#625]
When you start & stop `proxy.py` from command line, it works all fine. However, when using embedded `proxy.py` in your script, it doesn't totally destroy its workers. The workers are still shown on the Task Manager. I've to manually end the processes. 

Consider this example: 
```python
import ipaddress
import proxy

if __name__ == "__main__":
    proxy.main(
       hostname = ipaddress.IPv4Address("127.0.0.1"),
       port=8080,
       num_workers=1
    )
```

Now, compile this script: 
```
$ pyinstaller --onefile script.py
```

Now, when you run the compiled script: 
```
$ .\agent.exe
```

And then stop the agent, it would stop the main process which started `proxy.py` but the proxy.py processes still remains there until forcefully stopped from the task manager.

**Comment by abhinavsingh** [comment]
Do you force kill the agent?  If yes, then I can see why worker processes keep running because they are set as daemon i.e. keep running detached from the main process.  This was done to enforce proxy is running even if dispatcher thread errors out.  But is not what you want, but I think it will depend how are you terminating your agent.  Give it a signal 15 instead of kill 9 and it should also terminate the worker processes.  Let me know

**Comment by abhinavsingh** [comment]
@hash3liZer Can you share your `pyinstaller` setup?  So that I can reproduce and try the same locally.  I gave it a try and it runs into a `multiprocessing` import error loop when started.  Thank you!!!

**Comment by abhinavsingh** [comment]
@hash3liZer Hey, wanted to post an update about this issue.  https://github.com/abhinavsingh/proxy.py/pull/908 now registers signal handler and proxy instance will shutdown whenever the parent process detaches.  This may or may not work reliably on Windows, but I haven't tried it on Windows yet.
